### ISSUE TITLE
Passport version issue?

### ISSUE THREAD

**Issue by pkandarpa-cs** [ooade/next-apollo-auth#4]
> GraphQL Server Listening on Port 3000
```
/Users/pkandarpa/packages/next-apollo-auth/server/routes.js:9
                passport.authenticate('github', (err, user, { nextRoute }) => {
                                  ^
TypeError: Cannot destructure property `nextRoute` of 'undefined' or 'null'.
    at passport.authenticate (/Users/pkandarpa/packages/next-apollo-auth/server/routes.js:9:35)
    at Strategy.strategy.error (/Users/pkandarpa/packages/next-apollo-auth/node_modules/passport/lib/middleware/authentic
ate.js:353:18)
    at /Users/pkandarpa/packages/next-apollo-auth/node_modules/passport-oauth2/lib/strategy.js:166:34
    at /Users/pkandarpa/packages/next-apollo-auth/node_modules/passport-github/lib/strategy.js:77:16
    at /Users/pkandarpa/packages/next-apollo-auth/node_modules/oauth/lib/oauth2.js:209:7
    at passBackControl (/Users/pkandarpa/packages/next-apollo-auth/node_modules/oauth/lib/oauth2.js:134:9)
    at IncomingMessage.<anonymous> (/Users/pkandarpa/packages/next-apollo-auth/node_modules/oauth/lib/oauth2.js:157:7)
    at IncomingMessage.emit (events.js:132:15)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
```

**Comment by ooade** [comment]
So strange I just got to see this. Did you send `nextRoute` from services?

**Comment by ooade** [comment]
I guess there's no issue with this anymore. If it persists, feel free to re-open.
